### ISSUE TITLE
Practica 6 

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-9-practica-6-contrato-compilado-teamreciclenexus#2]
[Practica6-IngenieriaDeSoftware-LuzArleth-SaulLB.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-6-contrato-compilado-teamreciclenexus/files/15381960/Practica6-IngenieriaDeSoftware-LuzArleth-SaulLB.pdf)

**Comment by josealfredo79** [comment]
bien hecho y revisado..
